# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/ghtkn-go-sdk/refs/heads/main/json-schema/ghtkn.json
# ghtkn - https://github.com/suzuki-shunsuke/ghtkn
apps:
  - name: geeek-io-ghtkn/none # The name to identify the app
    client_id: Iv23libqzPliEVlXbfCe # Your GitHub App Client ID
