#:schema https://www.schemastore.org/taplo.json

[formatting]
	align_entries         = true
	indent_entries        = true
	indent_tables         = true
	reorder_inline_tables = true
	reorder_keys          = true
