# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

interval: 1s

set:
  - errexit
  - nounset

output: prefixed

includes:
  hook: tasks/hook
  check: tasks/check
  fix: tasks/fix

tasks:
  check:
    deps:
      - check:shfmt
      - check:shellcheck
      - check:hadolint

  fix:
    cmds:
      - task: fix:shfmt
      - task: fix:shellcheck

  ci:
    cmds:
      - task: fix
      - task: check
