# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

interval: 1s

set:
  - errexit
  - nounset

output:
  group:
    begin: '================ {{.TASK}} ================'
    end: '================================================================'

tasks:
  hook:post-create:
    desc: The hook runs after the container is created.
    summary: |-
      The hook runs after the container is created.
      It installs necessary tools and sets up the environment.
    cmd: run-dir tasks/hook/post-create
