#:schema https://mise.jdx.dev/schema/mise.json

min_version = '2025.9.19'

[tools]
	'node' = '24.9'

	'aqua:jdx/usage'         = '2.2.2'
	'aqua:microsoft/edit'    = '1.2.0'
	'aqua:sharkdp/bat'       = '0.25.0'
	'aqua:starship/starship' = '1.23.0'

	'aqua:FiloSottile/age' = '1.2.1'
	'aqua:getsops/sops'    = '3.10.2'

	'aqua:koalaman/shellcheck' = '0.11.0'
	'aqua:mvdan/sh'            = '3.12.0'

	'aqua:docker/cli'          = '28.4.0'
	'aqua:goodwithtech/dockle' = '0.4.15'
	'aqua:hadolint/hadolint'   = '2.14.0'

	'aqua:tamasfe/taplo' = '0.10.0'

	'aqua:astral-sh/uv' = '0.8.22'

[settings]
	gpg_verify   = true
	paranoid     = true
	pin          = true
	task_timings = true

	cache_prune_age                = '10d'
	task_output                    = 'replacing'
	unix_default_file_shell_args   = '/usr/bin/bash -o verbose -o xtrace'
	unix_default_inline_shell_args = '/usr/bin/bash -c -o verbose -o xtrace'

	[settings.status]
		missing_tools = 'always'
