x-anchors:
  service-common: &service-common
    attach: false
    init: true
    pull_policy: daily
    logging:
      driver: local

name: ${WORKSPACE_NAME}

services:
  dev:
    <<: *service-common
    hostname: dev
    pull_policy: build
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      pull: true
      args:
        WORKSPACE_NAME: ${WORKSPACE_NAME}
    volumes:
      - ..:/home/nonroot/${WORKSPACE_NAME}
      - dev-cache:/home/nonroot/.cache/
      - aqua:/home/nonroot/.local/share/aquaproj-aqua/
      - pnpm:/home/nonroot/.local/share/pnpm/store/
      - node-compile-cache:/home/nonroot/.node-compile-cache
      # For OrbStack
      - ~/.orbstack/run/docker.sock:/home/nonroot/docker.sock
      # For general Docker
      # - /var/run/docker.sock:/home/nonroot/docker.sock

volumes:
  dev-cache:
  aqua:
    name: aqua
  pnpm:
    name: pnpm
  node-compile-cache:
    name: node-compile-cache
