x-anchors:
  service-common: &service-common
    attach: false
    init: true
    pull_policy: daily
    logging:
      driver: local

name: ${WORKSPACE_NAME}

services:
  dev:
    <<: *service-common
    hostname: dev
    pull_policy: build
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      pull: true
    volumes:
      - ..:/home/nonroot/${WORKSPACE_NAME}
      - dev-cache:/home/nonroot/.cache/
      - aqua:/home/nonroot/.local/share/aquaproj-aqua/
      - npm:/home/nonroot/.npm/
      - bun:/home/nonroot/.bun/
      # For OrbStack
      - ~/.orbstack/run/docker.sock:/home/nonroot/docker.sock
      # For general Docker
      # - /var/run/docker.sock:/home/nonroot/docker.sock

volumes:
  dev-cache:
  aqua:
    name: aqua
  npm:
    name: npm
  bun:
    name: bun
