x-anchors:
  service-common: &service-common
    attach: false
    init: true
    pull_policy: daily
    logging:
      driver: local

name: ${WORKSPACE_NAME}

services:
  dev:
    <<: *service-common
    hostname: dev
    pull_policy: build
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      pull: true
    environment:
      SOPS_AGE_KEY_FILE: /home/nonroot/${WORKSPACE_NAME}/.gitignore.d/age.txt
      DOCKER_HOST: unix:///home/nonroot/docker.sock
      WORKSPACE_DIR: /home/nonroot/${WORKSPACE_NAME}
      MISE_GLOBAL_CONFIG_FILE: /home/nonroot/${WORKSPACE_NAME}/mise/config.toml
      MISE_TRUSTED_CONFIG_PATHS: /home/nonroot/${WORKSPACE_NAME}/mise/config.toml
    volumes:
      - ..:/home/nonroot/${WORKSPACE_NAME}
      - dev-cache:/home/nonroot/.cache/
      - mise:/home/nonroot/.local/share/mise/
      - npm:/home/nonroot/.npm/
      - bun:/home/nonroot/.bun/
      # For OrbStack
      - ~/.orbstack/run/docker.sock:/home/nonroot/docker.sock
      # For general Docker
      # - /var/run/docker.sock:/home/nonroot/docker.sock

volumes:
  dev-cache:
  mise:
    name: mise
  npm:
    name: npm
  bun:
    name: bun
