x-anchors:
  service-common: &service-common
    attach: false
    init: true
    pull_policy: daily
    logging:
      driver: local

name: ${WORKSPACE_NAME}

services:
  dev:
    <<: *service-common
    hostname: dev
    pull_policy: build
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      pull: true
      args:
        WORKSPACE_NAME: ${WORKSPACE_NAME}
    env_file:
      - ../.var.env
    volumes:
      - ..:${_HOME}/${WORKSPACE_NAME}
      - dev-cache:${_HOME}/.cache/
      - aqua:${_HOME}/.local/share/aquaproj-aqua/
      - pnpm:${_HOME}/.local/share/pnpm/store/
      - node-compile-cache:${_HOME}/.node-compile-cache/
      - uv:${_HOME}/.local/share/uv/
      # For OrbStack
      - ~/.orbstack/run/docker.sock:${_HOME}/docker.sock
      # For general Docker
      # - /var/run/docker.sock:${_HOME}/docker.sock

volumes:
  dev-cache:
  aqua:
    name: aqua
  pnpm:
    name: pnpm
  node-compile-cache:
    name: node-compile-cache
  uv:
    name: uv
