# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json

packages:
  - name: FiloSottile/age
    version: v1.2.1

  - name: docker/cli
    version: v28.5.0

  - name: fish-shell/fish-shell
    version: '4.1.1'

  - name: starship/starship
    version: v1.23.0
