# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json

packages:
  - name: FiloSottile/age
    version: v1.2.1
    tags:
      - bootstrap

  - name: cli/cli
    version: v2.81.0
    tags:
      - bootstrap

  - name: fish-shell/fish-shell
    version: '4.1.1'

  - name: starship/starship
    version: v1.23.0

  - name: jqlang/jq
    version: jq-1.8.1

  - name: docker/cli
    version: v28.5.0

  - name: zizmorcore/zizmor
    version: v1.14.2

  - name: nektos/act
    version: v0.2.82
