name: shfmt

run-name: >-
  ${{github.workflow}}
  for ${{github.ref_name}}
  by ${{github.triggering_actor}}
  on ${{github.event_name}}
  ${{github.run_attempt > 1 && format(' (attempt {0})', github.run_attempt)}}

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.sh'

jobs:
  shfmt:
    name: shfmt
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4.3.0
        with:
          path: ~/.local/share/aquaproj-aqua
          key: aqua-v2-${{runner.os}}-${{runner.arch}}-${{hashFiles('./.aqua/aqua.yaml', './.aqua/packages/local.yaml')}}
          restore-keys: |
            aqua-v2-${{runner.os}}-${{runner.arch}}-

      - uses: aquaproj/aqua-installer@v4.0.3
        with:
          aqua_version: v2.55.0
          aqua_opts: >-
            --only-link
            --tags ci
        env:
          AQUA_ENFORCE_CHECKSUM: true
          AQUA_ENFORCE_REQUIRE_CHECKSUM: true

      - run: ./scripts/shfmt.sh --diff .
